# Generated by Django 2.1 on 2019-03-15 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.TimeField(default=datetime.datetime(2019, 3, 15, 9, 20, 54, 142781, tzinfo=utc), null=True)),
                ('date', models.DateField(default=datetime.datetime(2019, 3, 15, 14, 50, 54, 143778), null=True)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
    ]
