# Generated by Django 2.1 on 2019-03-15 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 14, 52, 32, 831684), null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 15, 9, 22, 32, 831684, tzinfo=utc), null=True),
        ),
    ]
