# Generated by Django 2.1 on 2019-03-15 09:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_auto_20190315_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 15, 15, 4, 14, 679823), null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 15, 9, 34, 14, 679823, tzinfo=utc), null=True),
        ),
    ]
